### ISSUE TITLE
The reporter doesn't work on Windows

### ISSUE THREAD

**Issue by avdynut** [gusarin/jest-allure-reporter#1]
The reporter can't create _.xml_ files, because `testSuiteResults.testFilePath` on Windows looks like _'D:\Projects\apijesttests-master\tests\carts.tests.js'_. Need to remove symbol ':' and replace '\\'.
Or it can be `this.name =  testSuiteResults.testFilePath.split(/(\/|\\)/g).pop()`.
Also, please fix paths _'/tmp/allure-results/'_ to just _'allure-results/'_ for example. Otherwise the files are generated in _'D:\tmp\allure-results\'_ in my case.

**Comment by hroemer** [comment]
@avdynut thanks for you feedback, I added your changes and hope it also works on Windows now, but I can't test it, though!
@gusarin could you please check the PR #2?

**Comment by gusarin** [comment]
PR#2 is integrated and available in Node-Package version 1.2.3

**Comment by avdynut** [comment]
Now it works fine on Windows, thank you!
