### ISSUE TITLE
Getting json parse exception after running the test case successfully. Also can we provide some working example of this reporter? 

### ISSUE THREAD

**Issue by shandilyamaramraju** [gusarin/jest-allure-reporter#4]
com.fasterxml.jackson.core.JsonParseException: Unexpected character '[' (code 91) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]

**Comment by lightsofapollo** [comment]
Output of the XML files is [object ArrayBuffer] a "toString" is missing somewhere. On it.
